### ISSUE TITLE
Umami deployment instructions

### ISSUE THREAD

**Issue by 4ortytwo** [code-fabrik/open-knowledge#1]
Hi! Didn't expect to find something like this, thank you. 

http://knowledge.code-fabrik.ch/software/dokku/docker-image-deploys/umami.html

I've followed the steps and managed to get to umami login screen but have no idea how I could have created a database user and password. And what would be the `DATABASE_URL` in this case? 

Could it be that the guide needs to be supplemented or can my question be answered somewhere else?

**Comment by LukasSkywalker** [comment]
Hi
I left it out but I will try to add it as soon as possible.
Postgresql should be included in the docker file referenced. No need to install an external DB. The default username is `admin` and the default password is `umami` if i remember correctly.
Hope that helps :)

**Comment by 4ortytwo** [comment]
Thanks! I started from scratch and am at the login screen again. I get `internal server error` if I enter the default credentials. 
And this is what's in the logs. 
Could you point me in the right direction? 

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/44406493/114536398-5490ec80-9c51-11eb-8f68-d6f78ec4a128.png">

**Comment by 4ortytwo** [comment]
I resolved my issue and could make a PR tonight to adjust the instructions and close this issue, maybe you could check if I made it extra complicated then?
